name: Trivy Secret Scanning

on:
  pull_request:
    paths:
      - '**/*.dockerfile'
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.json'

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy secret scanning
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'secret'          # Defines the type of scan (secret scanning)
          scanners: 'secret'           # Specify that we're scanning for secrets
          format: 'table'              # Format the output as a table
          exit-code: '0'  # Ensures the job keeps running regardless of vulnerabilities found
          ignore-unfixed: true
          output: 'trivy-results.txt'
          
      - name: Check if Trivy results were generated
        run: |
          if [ ! -s trivy-results.txt ]; then
            echo "No Trivy results found." > formatted_results.txt
          else
            cat trivy-results.txt > formatted_results.txt
          fi
          cat formatted_results.txt  # Log the content for debugging

      - name: Set Trivy results as output
        id: set_results
        run: |
          echo "results<<EOF" >> $GITHUB_ENV
          cat formatted_results.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Comment formatted scan results on PR
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Trivy Secret Scanning Results

            Please find the scan results below:

            ```
            ${{ env.results }}
            ```
